### ISSUE TITLE
Info page is done

### ISSUE THREAD

**Issue by nicknamekeeper** [nicknamekeeper/researcher#12]
Make info page with:
- [x] Authors
- [x] Contributors
- [x] Fonts
- [x] Emoji Fonts
- [x] Icons
- [x] Libraries
- [x] Licenses

### To do
- [x] Create `InfoView.vue`

**Comment by 00xDEAD10CC** [comment]
Depends on:
- #1 

'cause we should work with leftmenu icon  `InfoIcon.vue`
